create database sporty_shoes;
use sporty_shoes;
create table products(Id int,Brand varchar(20),Mrp int,Category varchar(10),Description varchar(50),Image varchar(255));
insert into products values(1,'Nike','3695','men','Price inclusive of all taxes','/resources/images/boy/nikeboy.png');
insert into products values(2,'Adidas','2650','men','Price inclusive of all taxes','/resources/images/boy/adidasboy.png');
insert into products values(3,'Reebok','4000','men','Price inclusive of all taxes','/resources/images/boy/reebokboy.jpg');
insert into products values(4,'Puma','2000','men','Price inclusive of all taxes','/resources/images/boy/pumaboy.png');
insert into products values(5,'Skechers','5000','men','Price inclusive of all taxes','/resources/images/boy/skechersboy.png');
insert into products values(6,'New Balance','3595','men','Price inclusive of all taxes','/resources/images/boy/newbalanceboy.png');
insert into products values(7,'Under Armour','1298','men','Price inclusive of all taxes','/resources/images/boy/underarmourboy.png');
insert into products values(8,'Xtep','2600','men','Price inclusive of all taxes','/resources/images/boy/xtepboy.png');
insert into products values(9,'Asics','4278','men','Price inclusive of all taxes','/resources/images/boy/asicsboy.png');
insert into products values(10,'Brooks','1592','men','Price inclusive of all taxes','/resources/images/boy/brooksboy.png');
insert into products values(11,'Nike','3695','women','Price inclusive of all taxes','/resources/images/girl/nikegirl.png');
insert into products values(12,'Adidas','2650','women','Price inclusive of all taxes','/resources/images/girl/adidasgirl.png');
insert into products values(13,'Reebok','4000','women','Price inclusive of all taxes','/resources/images/girl/reebokgirl.png');
insert into products values(14,'Puma','2000','women','Price inclusive of all taxes','/resources/images/girl/pumagirl.png');
insert into products values(15,'Skechers','5000','women','Price inclusive of all taxes','/resources/images/girl/skechersgirl.png');
insert into products values(16,'New Balance','3595','women','Price inclusive of all taxes','/resources/images/girl/newbalancegirl.png');
insert into products values(17,'Under Armour','1298','women','Price inclusive of all taxes','/resources/images/girl/underarmourgirl.png');
insert into products values(18,'Xtep','2600','women','Price inclusive of all taxes','/resources/images/girl/xtepgirl.png');
insert into products values(19,'Asics','4278','women','Price inclusive of all taxes','/resources/images/girl/asicsgirl.png');
insert into products values(20,'Brooks','1592','women','Price inclusive of all taxes','/resources/images/girl/brooksgirl.jpg');
select * from products;
set sql_safe_updates=0;
create table Users(Id int,username varchar(50),password varchar(50));
insert into users values(1,'admin','admin');
insert into users values(2,'tek','123');
select * from users;
create table cart(Id int,Brand varchar(20),Mrp varchar(20),Category varchar(10),Description varchar(50),Image varchar(255));
insert into cart values(1,'Nike','3,695','men','Price inclusive of all taxes','/resources/images/boy/nikeboy.png');
select * from cart;
create table orders(orderid int auto_increment,pcode int,username varchar(30),email varchar(40),mobile varchar(10),price int,location varchar(40),date date,category char(10),primary key(orderid),brand varchar(20),image varchar(50));
select * from orders;
